#ifndef ARCHIVETYPES_H
#define ARCHIVETYPES_H

#include "../CommonTypes.h"

#define ARCHIVETYPE_GOB 0
#define ARCHIVETYPE_LAB 1
#define ARCHIVETYPE_LFD 2
#define ARCHIVETYPE_ART 3
#define ARCHIVETYPE_RFF 4
#define ARCHIVETYPE_BSA 5
#define ARCHIVETYPE_NONE 255

#endif //ARCHIVETYPES_H