#ifndef TEXTURETYPES_H
#define TEXTURETYPES_H

#include "../CommonTypes.h"

#define TEXTURETYPE_ART 0
#define TEXTURETYPE_PCX 1
#define TEXTURETYPE_IMG 2
#define TEXTURETYPE_COUNT 3
#define TEXTURETYPE_NONE 255

#endif //TEXTURETYPES_H